### ISSUE TITLE
Cannot install directly with pip

### ISSUE THREAD

**Issue by mpariente** [fgnt/pb_bss#11]
### Steps to reproduce
On a fresh python install
```
git clone https://github.com/fgnt/pb_bss
cd pb_bss
pip install numpy Cython
pip install -e .
```

### Solution so far 
- Comment  [these lines](https://github.com/fgnt/pb_bss/blob/master/setup.py#L28) 
- `pip install -e .`
- Uncomment the same lines
- `pip install -e .`

Ends up working

**Comment by mpariente** [comment]
The stack trace (it's huge)
```
    ERROR: Command errored out with exit status 1:
     command: /home/mparient/.virtualenvs/reproduce/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mparient/code_perso/cloned/pb_bss/setup.py'"'"'; __file__='"'"'/home/mparient/code_perso/cloned/pb_bss/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/mparient/code_perso/cloned/pb_bss/
    Complete output (488 lines):
    /home/mparient/.virtualenvs/reproduce/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/mparient/code_perso/cloned/pb_bss/pb_bss/extraction/cythonized/c_eig.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # encoding: utf-8
    
    cimport numpy as np
    import numpy as np
    from scipy.linalg.cython_lapack cimport zggev
    ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:5:0: 'scipy/linalg/cython_lapack.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # encoding: utf-8
    
    cimport numpy as np
    import numpy as np
    from scipy.linalg.cython_lapack cimport zggev
    ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:5:0: 'scipy/linalg/cython_lapack/zggev.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef complex* b_ptr = &b_view[0, 0, 0]
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
       ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:69:4: 'zggev' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef complex* b_ptr = &b_view[0, 0, 0]
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                             ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:69:26: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef complex* b_ptr = &b_view[0, 0, 0]
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                 ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:69:30: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef complex* b_ptr = &b_view[0, 0, 0]
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                        ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:69:37: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef complex* b_ptr = &b_view[0, 0, 0]
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                              ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:69:43: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef complex* b_ptr = &b_view[0, 0, 0]
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                                     ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:69:50: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef complex* b_ptr = &b_view[0, 0, 0]
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                                           ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:69:56: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef complex* b_ptr = &b_view[0, 0, 0]
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                                                      ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:69:67: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_tmp_ptr, &tmp_size, rwork_ptr, &INFO)
              ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:70:11: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_tmp_ptr, &tmp_size, rwork_ptr, &INFO)
                      ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:70:19: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_tmp_ptr, &tmp_size, rwork_ptr, &INFO)
                             ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:70:26: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_tmp_ptr, &tmp_size, rwork_ptr, &INFO)
                                     ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:70:34: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_tmp_ptr, &tmp_size, rwork_ptr, &INFO)
                                            ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:70:41: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_tmp_ptr, &tmp_size, rwork_ptr, &INFO)
                                                          ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:70:55: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_tmp_ptr, &tmp_size, rwork_ptr, &INFO)
                                                                     ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:70:66: Cannot convert 'double *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        cdef np.ndarray[double, ndim=1] rwork = np.empty(8*sensors, dtype=np.float64)
        cdef double* rwork_ptr = <double*> rwork.data
    
        zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_tmp_ptr, &tmp_size, rwork_ptr, &INFO)
                                                                                ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:70:77: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef size_t m
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
           ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:102:8: 'zggev' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef size_t m
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                 ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:102:30: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef size_t m
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                     ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:102:34: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef size_t m
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                            ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:102:41: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef size_t m
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                                  ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:102:47: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef size_t m
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                                         ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:102:54: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef size_t m
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                                               ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:102:60: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef size_t m
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
                                                                          ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:102:71: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_ptr, &work_size, rwork_ptr, &INFO)
              ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:103:11: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_ptr, &work_size, rwork_ptr, &INFO)
                      ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:103:19: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_ptr, &work_size, rwork_ptr, &INFO)
                             ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:103:26: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_ptr, &work_size, rwork_ptr, &INFO)
                                     ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:103:34: Cannot convert 'int *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_ptr, &work_size, rwork_ptr, &INFO)
                                            ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:103:41: Cannot convert 'double complex *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_ptr, &work_size, rwork_ptr, &INFO)
                                                      ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:103:51: Cannot convert 'int *' to P- `pip install -e .`ython object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_ptr, &work_size, rwork_ptr, &INFO)
                                                                  ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:103:63: Cannot convert 'double *' to Python object
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for f in range(bins):
            a_ptr = a_ptr_global + sensors_square * f
            b_ptr = b_ptr_global + sensors_square * f
            vr_ptr = vr_ptr_global + sensors_square * f
            zggev(&JOBVL, &JOBVR, &N, a_ptr, &LDA, b_ptr, &LDB, alpha_ptr, beta_ptr,
               vl_ptr, &LDVL, vr_ptr, &LDVR, work_ptr, &work_size, rwork_ptr, &INFO)
                                                                             ^
    ------------------------------------------------------------
    
    pb_bss/extraction/cythonized/c_eig.pyx:103:74: Cannot convert 'int *' to Python object
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mparient/code_perso/cloned/pb_bss/setup.py", line 35, in <module>
        'pb_bss/extraction/cythonized/c_eig.pyx',
      File "/home/mparient/.virtualenvs/reproduce/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
        cythonize_one(*args)
      File "/home/mparient/.virtualenvs/reproduce/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: pb_bss/extraction/cythonized/c_eig.pyx
    Compiling pb_bss/extraction/cythonized/get_gev_vector.pyx because it depends on /home/mparient/.virtualenvs/reproduce/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd.
    Compiling pb_bss/extraction/cythonized/c_eig.pyx because it depends on /home/mparient/.virtualenvs/reproduce/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd.
    [1/2] Cythonizing pb_bss/extraction/cythonized/c_eig.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by boeddeker** [comment]
I think this error has something to do with scipy:
```
...
pb_bss/extraction/cythonized/c_eig.pyx:5:0: 'scipy/linalg/cython_lapack.pxd' not found
...
```
We try to figure out why this happens.
Maybe the solution is to install also scipy (`pip install numpy scipy Cython`) before installing `pb_bss` as it is done in 
https://github.com/fgnt/pb_bss/blob/58e3c5e211814d2c49cb9fa9a8299ef1ad535f4b/azure-pipelines.yml#L23

**Comment by boeddeker** [comment]
I found a solution for this error.
We had `scipy` as a dependency through `scikit-learn`.
It seems to be, that when installing this package it first tries to compile the cython code before installing the dependencies. So you have to manually install scipy, then the installation will work.

In #13 I improved the error msg.

Thank you for reporting this.

**Comment by mpariente** [comment]
Great, thanks for the quick fix !
